POST http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RoYXNoQGVtYWlsLmNvbSIsImV4cCI6MTcyNzk2NTQwMiwidXNlcklkIjoxfQ.fOeII6xFJUfDnwgHzZfghKo0e_arn78Qyo3eIIwR6xw
